### ISSUE TITLE
Doesn't open with error.

### ISSUE THREAD

**Issue by tahacelik20181** [rosmord/jsesh#34]
I tried to download latest version of JSesh and run it but it gave me a error and it doesn't open. I reinstalled but still happening. I'm putting the error log file here:
[errorinfo.txt](https://github.com/rosmord/jsesh/files/8011169/errorinfo.txt)
What's problem?

**Comment by tahacelik20181** [comment]
Oh.. I just change language of my windows to English from Turkish. There's no problem now. I hope will be fix in later.

**Comment by Bikenkhet** [comment]
The Turkish locale often causes issues because it has dotted and dotless I, which thus get uppercased and lowercased differently to most Latin-based alphabets. Fixing this requires specifying a locale in all instances where a string is uppercased or lowercased apart from human interface text.

The point of failure given:
https://github.com/rosmord/jsesh/blob/7d8d1c66cce21154cc3b69b151970c6832dda4ee/jsesh/src/main/java/jsesh/hieroglyphs/data/io/SignDescriptionBuilderToHieroglyphDatabaseAdapter.java#L64

@tahacelik20181 I imagine it will be a pain to fix so I wouldn't expect it any time soon.

**Comment by tahacelik20181** [comment]
Oh i see, no problem it can be wait. Already there's quick easy fix as like changing language of windows. Thanks for response.

**Comment by Bikenkhet** [comment]
On review I think this would be quite doable. There are 15 instances of toUpperCase() and 50 instances of toLowerCase() that need to be checked. The issue should be reopened, this is for Serge to decide, I'm just offering my thoughts.

**Comment by tahacelik20181** [comment]
Oh I just saw the reopen button, it was unnecessary to open a new one though, sorry.
